#! /bin/sh

printf_error_msg() {
    printf "\e[31mERROR\e[0m: %s\n" "$1"
}

printf_warn_msg() {
    printf "\e[33mWARN\e[0m: %s\n" "$1"
}

create_post() {
    [ -z "$1" ] && {
        printf_error_msg "Require post name"
        exit 1
    }

    hugo new "posts/$1.md"
}

remove_post() {
    [ -z "$1" ] && {
        printf_error_msg "Require post name"
        exit 1
    }

    rm "content/posts/$1.md"
}

check_posts() {
    find content/posts -maxdepth 2 -type f -name "*.md" | while read -r entry; do

        # check windows format
        if file "$entry" | grep "CRLF" -q; then
            printf_warn_msg "Found Windows format file \"${entry#content/posts/}\""
        fi

        # check heading 1
        head -n 20 "$entry" | grep -E '^#\s+.*' -q && printf_warn_msg "Found heading 1 in \"${entry#content/posts/}\""

        # check frontmatter
        head -n 20 "$entry" | awk '
            BEGIN { state = 0; quit = 1 }
            state == 0 && /^[[:space:]]*$/ { next }        # 跳过前言前的空行
            state == 0 && $0 == "+++" { state = 1; next }  # 找到起始标记
            state == 0 { exit 1 }                          # 无任何前言标记
            state == 1 && $0 == "+++" { quit = 0; exit 0 } # 找到结束标记
            END { if (state == 1 && quit == 1) exit 1 }
    ' || printf_warn_msg "No frontmatter found in \"${entry#content/posts/}\""

    done
}

[ -f hugo.toml ] || {
    printf_error_msg "Can't found hugo.toml. Run script in site root directory."
    exit 1
}

[ -d './content/posts' ] || {
    printf_error_msg "Can't found content/posts directory. Run script in site root directory."
    exit 1
}

case "$1" in
check) check_posts ;;
new) create_post "$2" ;;
rm) remove_post "$2" ;;
esac
